### ISSUE TITLE
Missing `build:js` command in package.json

### ISSUE THREAD

**Issue by MariusE** [AleksandrHovhannisyan/11ty-sass-images-seo#2]
In the `package.json` there is this build command

```
"build": "run-s build:html build:css build:js",
```
which would run `build:js`.

But there is no `build:js` command. So the build fails with
```
ERROR: Task not found: "build:js"
```

**Comment by AleksandrHovhannisyan** [comment]
Good catch! Will push up a fix for this shortly.
